-- 사원일정
DROP TABLE IF EXISTS `final`.companyschedule;
CREATE TABLE `final`.companyschedule
(
    `COMPANYSCHEDULE_ID`      BIGINT       NOT NULL AUTO_INCREMENT COMMENT '사내일정코드',
    `COMPANYSCHEDULE_EMP_ID`  BIGINT       NOT NULL COMMENT '사원코드',
    `COMPANYSCHEDULE_CONTENT` VARCHAR(255) NOT NULL COMMENT '사내일정날짜',
    `COMPANYSCHEDULE_DATE`    DATE         NOT NULL COMMENT '사내일정내용',
    PRIMARY KEY (`COMPANYSCHEDULE_ID`)
) ENGINE = InnoDB COMMENT '사내일정'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.companyschedule
    ADD CONSTRAINT `FK_COMPANYSCHEDULE_EMP` FOREIGN KEY (`COMPANYSCHEDULE_EMP_ID`) REFERENCES `final`.emp (`EMP_ID`);