-- 메모
DROP TABLE IF EXISTS `final`.memo;
CREATE TABLE `final`.memo
(
    `MEMO_ID`      BIGINT       NOT NULL AUTO_INCREMENT COMMENT '메모코드',
    `MEMO_EMP_ID`  BIGINT       NOT NULL COMMENT '사원코드',
    `MEMO_CONTENT` VARCHAR(255) NULL COMMENT '메모내용',
    PRIMARY KEY (`MEMO_ID`)
) ENGINE = InnoDB COMMENT '메모'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.memo
    ADD CONSTRAINT `FK_MEMO_EMP` FOREIGN KEY (`MEMO_EMP_ID`) REFERENCES `final`.emp (`EMP_ID`);