-- 메모
DROP TABLE IF EXISTS `final`.message;
CREATE TABLE `final`.message
(
    `MESSAGE_ID`              BIGINT       NOT NULL AUTO_INCREMENT COMMENT '메모코드',
    `MESSAGE_SUBJECT`         VARCHAR(255) NOT NULL COMMENT '제목',
    `MESSAGE_CONTENT`         VARCHAR(255) NOT NULL COMMENT '내용',
    `MESSAGE_STATUS`          VARCHAR(255) NOT NULL COMMENT '상태',
    `MESSAGE_SENDER_EMP_ID`   BIGINT       NOT NULL COMMENT '보낸사람',
    `MESSAGE_RECEIVER_EMP_ID` BIGINT       NOT NULL COMMENT '받는사람',
    PRIMARY KEY (`MESSAGE_ID`)
) ENGINE = InnoDB COMMENT '쪽지'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.message
    ADD CONSTRAINT `FK_MESSAGE_SENDER` FOREIGN KEY (`MESSAGE_SENDER_EMP_ID`) REFERENCES `final`.emp (`EMP_ID`);
ALTER TABLE `final`.message
    DROP CONSTRAINT `FK_MESSAGE_RECEIVER`