-- 휴가
DROP TABLE IF EXISTS `final`.vacation;
CREATE TABLE `final`.vacation
(
    `VACATION_ID`            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '휴가코드',
    `VACATION_EMP_ID`        BIGINT       NOT NULL COMMENT '사원코드',
    `VACATION_TOTALVACATION` INT          NOT NULL COMMENT '총 휴가',
    `VACATION_TOTALDAYOFF`   INT          NOT NULL COMMENT '총 연차',
    `VACATION_USEDCOUNT`     INT          NOT NULL COMMENT '사용 횟수',
    `VACATION_STARTDATE`     DATE         NULL COMMENT '시작일',
    `VACATION_ENDDATE`       DATE         NULL COMMENT '종료일',
    `VACATION_WHY`           VARCHAR(255) NULL COMMENT '사유',
    PRIMARY KEY (`VACATION_ID`)
) ENGINE = InnoDB COMMENT '사원근태'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.vacation
    ADD CONSTRAINT `FK_VACATION_EMP` FOREIGN KEY (`VACATION_EMP_ID`) REFERENCES `final`.emp (`EMP_ID`);