-- 회원
DROP TABLE IF EXISTS `final`.member;
CREATE TABLE `final`.member
(
    `MEMBER_ID`            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '회원코드',
    `MEMBER_NAME`          VARCHAR(255) NOT NULL COMMENT '이름',
    `MEMBER_EMAIL`         VARCHAR(255) NOT NULL COMMENT '이메일',
    `MEMBER_PASSWORD`      VARCHAR(255) NOT NULL COMMENT '비밀번호',
    `MEMBER_PHONENUMBER`   VARCHAR(255) NOT NULL COMMENT '휴대폰번호',
    `MEMBER_BIRTHDAY`      DATE         NOT NULL COMMENT '생년월일',
    `MEMBER_JOINDATE`      DATE         NOT NULL COMMENT '회원 가입일',
    `MEMBER_RATEPLAN`      VARCHAR(255) NULL COMMENT '이용요금제',
    `MEMBER_PAYMENTPRICE`  INT          NULL COMMENT '결제금액',
    `MEMBER_PAYMENTDATE`   DATETIME     NULL COMMENT '결제일',
    `MEMBER_PAYMENTBANK`   VARCHAR(255) NULL COMMENT '결제은행',
    `MEMBER_ACCOUNTNUMBER` VARCHAR(255) NULL COMMENT '결제계좌',
    PRIMARY KEY (`MEMBER_ID`)
) ENGINE = InnoDB COMMENT '회원'
  AUTO_INCREMENT = 1;