-- 공지사항파일
DROP TABLE IF EXISTS `final`.noticefile;
CREATE TABLE `final`.noticefile
(
    `NOTICEFILE_ID`        BIGINT       NOT NULL AUTO_INCREMENT COMMENT '공지사항파일코드',
    `NOTICEFILE_NOTICE_ID` BIGINT NOT NULL COMMENT '공지사항코드',
    `NOTICEFILE_UPLOADFILE_ID` BIGINT NOT NULL COMMENT '업로드파일코드',
    PRIMARY KEY (`NOTICEFILE_ID`)
) ENGINE = InnoDB COMMENT '공지사항파일'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.noticefile
    ADD CONSTRAINT `FK_NOTICEFILE_NOTICE` FOREIGN KEY (`NOTICEFILE_NOTICE_ID`) REFERENCES `final`.notice (`NOTICE_ID`);
ALTER TABLE `final`.noticefile
    ADD CONSTRAINT `FK_NOTICEFILE_UPLOADFILE` FOREIGN KEY (`NOTICEFILE_UPLOADFILE_ID`) REFERENCES `final`.uploadfile (`UPLOADFILE_ID`);