-- 공지사항파일
DROP TABLE IF EXISTS `final`.notice_file;
CREATE TABLE `final`.notice_file
(
    `NOTICEFILE_ID`        BIGINT       NOT NULL AUTO_INCREMENT COMMENT '공지사항파일코드',
    `NOTICEFILE_NOTICE_ID` BIGINT       NOT NULL COMMENT '공지사항코드',
    `NOTICEFILE_NAME`      VARCHAR(255) NOT NULL COMMENT '공지사항파일이름',
    `NOTICEFILE_PATH`      VARCHAR(255) NOT NULL COMMENT '공지사항파일경로',
    `NOTICEFILE_EXTENSION` VARCHAR(255) NOT NULL COMMENT '파일 확장자',
    PRIMARY KEY (`NOTICEFILE_ID`)
) ENGINE = InnoDB COMMENT '공지사항파일'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.notice_file
    ADD CONSTRAINT `FK_NOTICEFILE_NOTICE` FOREIGN KEY (`NOTICEFILE_NOTICE_ID`) REFERENCES `final`.notice (`NOTICE_ID`);