-- 결재파일
DROP TABLE IF EXISTS `final`.approvalfile;
CREATE TABLE `final`.approvalfile
(
    `APPROVALFILE_ID`          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '결재파일코드',
    `APPROVALFILE_APPROVAL_ID` BIGINT       NOT NULL COMMENT '결재코드',
    `APPROVALFILE_NAME`        VARCHAR(255) NOT NULL COMMENT '결재파일이름',
    `APPROVALFILE_ORIGINNAME`  VARCHAR(255) NOT NULL COMMENT '결재파일원본이름',
    `APPROVALFILE_PATH`        VARCHAR(255) NOT NULL COMMENT '결재파일경로',
    PRIMARY KEY (`APPROVALFILE_ID`)
) ENGINE = InnoDB COMMENT '결재파일'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.APPROVALFILE
    ADD CONSTRAINT `FK_APPROVALFILE_APPROVAL` FOREIGN KEY (`APPROVALFILE_APPROVAL_ID`) REFERENCES `final`.approval (`APPROVAL_ID`);