-- 결재
DROP TABLE IF EXISTS `final`.approval;
CREATE TABLE `final`.approval
(
    `APPROVAL_ID`               BIGINT       NOT NULL AUTO_INCREMENT COMMENT '결재코드',
    `APPROVAL_EMP_ID`           BIGINT       NOT NULL COMMENT '사원코드',
    `APPROVAL_SUBJECT`          VARCHAR(255) NOT NULL COMMENT '결재제목',
    `APPROVAL_CONTENT`          VARCHAR(255) NOT NULL COMMENT '결재내용',
    `APPROVAL_CHECK`            VARCHAR(255) NOT NULL COMMENT '결재상태',
    `APPROVAL_CHECKMAN`         VARCHAR(255) NOT NULL COMMENT '결재승인자',
    `APPROVAL_CHECKMANPOSITION` VARCHAR(255) NOT NULL COMMENT '결재승인자직급',
    `APPROVAL_UPLOADDATE`       DATETIME     NOT NULL COMMENT '결재올린날짜',
    `APPROVAL_BACKDATE`         DATETIME     NULL COMMENT '결재반려날짜',
    `APPROVAL_SUCCESSDATE`      DATETIME     NULL COMMENT '결재승인날짜',
    PRIMARY KEY (`APPROVAL_ID`)
) ENGINE = InnoDB COMMENT '결재'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.approval
    ADD CONSTRAINT `FK_APPROVAL_EMP` FOREIGN KEY (`APPROVAL_EMP_ID`) REFERENCES `final`.emp (`EMP_ID`);