-- 결재파일
DROP TABLE IF EXISTS `final`.approvalfile;
CREATE TABLE `final`.approvalfile
(
    `APPROVALFILE_ID`          BIGINT       NOT NULL AUTO_INCREMENT COMMENT '결재파일코드',
    `APPROVALFILE_APPROVAL_ID` BIGINT       NOT NULL COMMENT '결재코드',
    `APPROVALFILE_UPLOADFILE_ID` BIGINT NOT NULL COMMENT '업로드파일코드',
    PRIMARY KEY (`APPROVALFILE_ID`)
) ENGINE = InnoDB COMMENT '결재파일'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.approvalfile
    ADD CONSTRAINT `FK_APPROVALFILE_APPROVAL` FOREIGN KEY (`APPROVALFILE_APPROVAL_ID`) REFERENCES `final`.approval (`APPROVAL_ID`);
ALTER TABLE `final`.approvalfile
    ADD CONSTRAINT `FK_APPROVALFILE_UPLOADFILE` FOREIGN KEY (`APPROVALFILE_UPLOADFILE_ID`) REFERENCES `final`.uploadfile (`UPLOADFILE_ID`);