-- 영상
DROP TABLE IF EXISTS `final`.movie;
CREATE TABLE `final`.movie
(
    `MOVIE_ID`          VARCHAR(255) NOT NULL COMMENT '영상 코드',
    `MOVIE_KRNAME`      VARCHAR(255) NULL COMMENT '영화명(한글)',
    `MOVIE_OGNAME`      VARCHAR(255) NULL COMMENT '영화명(원제)',
    `MOVIE_RELEASEDATE` DATE         NULL COMMENT '개봉일',
    `MOVIE_RATING`        VARCHAR(255) NULL COMMENT '평점',
    `MOVIE_OVERVIEW`    LONGTEXT NULL COMMENT '줄거리(개요)',
    `MOVIE_POSTERPATH`  VARCHAR(255) NULL COMMENT '이미지',
    PRIMARY KEY (`MOVIE_ID`)
) ENGINE = InnoDB COMMENT '영상';