-- 서비스영상
DROP TABLE IF EXISTS `final`.SERVICEMOVIE;
CREATE TABLE `final`.SERVICEMOVIE
(
    `SERVICEMOVIE_ID`            BIGINT       NOT NULL AUTO_INCREMENT COMMENT '서비스영상코드',
    `SERVICEMOVIE_MOVIE_ID`      VARCHAR(255) NOT NULL COMMENT '영상 코드',
    `SERVICEMOVIE_AMOUNT`        INT          NOT NULL COMMENT '판권금액',
    `SERVICEMOVIE_PAYMENTDATE`   DATETIME     NOT NULL COMMENT '판권결제일',
    `SERVICEMOVIE_PAYMENTBANK`   VARCHAR(255) NOT NULL COMMENT '결제은행',
    `SERVICEMOVIE_ACCOUNTNUMBER` VARCHAR(255) NOT NULL COMMENT '결제계좌',
    PRIMARY KEY (`SERVICEMOVIE_ID`)
) ENGINE = InnoDB COMMENT '서비스영상'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.SERVICEMOVIE
    ADD CONSTRAINT `FK_SERVICEMOVIE_EMP` FOREIGN KEY (`SERVICEMOVIE_MOVIE_ID`) REFERENCES `final`.movie (`MOVIE_ID`);
