-- 게시판파일
DROP TABLE IF EXISTS `final`.uploadfile;
CREATE TABLE `final`.uploadfile
(
    `UPLOADFILE_ID`         BIGINT       NOT NULL AUTO_INCREMENT COMMENT '파일코드',
    `UPLOADFILE_CREATEDDATE`   DATETIME       NOT NULL COMMENT '파일생성날짜',
    `UPLOADFILE_FSCHEMA` ENUM('notice', 'board', 'approval', 'emppicture'), -- SchemaType enum에 맞게 열거형 값 정의
    `UPLOADFILE_UUID` VARCHAR(255) NOT NULL COMMENT '파일식별자',
    `UPLOADFILE_NAME` VARCHAR(255) NOT NULL COMMENT '파일이름',
    `UPLOADFILE_EXTENSION` VARCHAR(255) NOT NULL COMMENT '파일확장자',
    `UPLOADFILE_PATH` VARCHAR(255) NOT NULL COMMENT '파일경로',
    `UPLOADFILE_SIZE` BIGINT NOT NULL COMMENT '파일크기',
    PRIMARY KEY (`UPLOADFILE_ID`)
) ENGINE = InnoDB COMMENT '업로드파일'
  AUTO_INCREMENT = 1;
