-- 게시판파일
DROP TABLE IF EXISTS `final`.boardfile;
CREATE TABLE `final`.boardfile
(
    `BOARDFILE_ID`         BIGINT       NOT NULL AUTO_INCREMENT COMMENT '게시판파일코드',
    `BOARDFILE_BOARD_ID`   BIGINT       NOT NULL COMMENT '게시판코드',
    `BOARDFILE_UPLOADFILE_ID` BIGINT NOT NULL COMMENT '업로드파일코드',
    PRIMARY KEY (`BOARDFILE_ID`)
) ENGINE = InnoDB COMMENT '게시판파일'
  AUTO_INCREMENT = 1;

ALTER TABLE `final`.boardfile
    ADD CONSTRAINT `FK_BOARDFILE_BOARD` FOREIGN KEY (`BOARDFILE_BOARD_ID`) REFERENCES `final`.board (`BOARD_ID`);
ALTER TABLE `final`.boardfile
    ADD CONSTRAINT `FK_BOARDFILE_UPLOADFILE` FOREIGN KEY (`BOARDFILE_UPLOADFILE_ID`) REFERENCES `final`.uploadfile (`UPLOADFILE_ID`);